### ISSUE TITLE
how about the continuous variable?

### ISSUE THREAD

**Issue by a3661008** [jfpuget/LibFM_in_Keras#2]
hi，
as we can see  from the codes:
i):features = ['os', 'device', 'app']
f_size  = [int(data[f].max()) + 1 for f in features]

ii) def get_embed(x_input, x_size, k_latent):
    if x_size > 0: #category
        embed = Embedding(x_size, k_latent, input_length=1, 
                          embeddings_regularizer=l2(embedding_reg))(x_input)
        embed = Flatten()(embed)
    else:
        embed = Dense(k_latent, kernel_regularizer=l2(embedding_reg))(x_input)
    return embed

iii) biases = [get_embed(x, size, 1) for (x, size) in zip(input_x, f_size)]   
 factors = [get_embed(x, size, k_latent) for (x, size) in zip(input_x, f_size)]

in the demo,there are all the category variable in the data,
can you show us  how to handle with continuous variable?or make  continuous variable into bins?
looking for your reply!
^_^

**Comment by jfpuget** [comment]
The code handles numerical features.  You need to pass a size of 0 for these features.  See the get_embed() function code.
