### ISSUE TITLE
input data format

### ISSUE THREAD

**Issue by algila** [jfpuget/LibFM_in_Keras#3]
Hi,
Many thanks sharing this code.
Having the output file, how is it possible to connect it to the original dataset ? I'm using  panda, is there any special command doing it ? Appear to me that the usual `"merge on"` command is not working with multiple columns

**Comment by algila** [comment]
I solved by my self just listing in an array the list of keys/category in `on` parameter of `merge` instruction

**Comment by jfpuget** [comment]
I joined the output with the original data, separately on train and test.  As you did, you need to use the columns that are aggregated here as keys for merge.
